import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {useContext, useEffect} from "react";
import {GlobalContext} from "../components/GlobalProvider";
import {useRouter} from "next/router";

export default function Home() {
    const {user} = useContext(GlobalContext)
    const router = useRouter();

    useEffect(() => {
        console.log(user)
        if (!user) {
            router.push('/login')
        }
    }, [user, router])


    return (
        <div className={styles.container}>
            <Head>
                <title>Bad Bank</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>


                {user ? <h1 className={styles.title}> Welcome </h1> : <h1 className={styles.title}> Please Login </h1>}

            </main>
        </div>
    )
}
