name: npm test
on: [ push ]

env:
  MONGODB_TEST_URI: mongodb+srv://JoseNaime:Lmzqfl11150@bad-bank.2dfm7.mongodb.net/webCollection?retryWrites=true&w=majority

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [ 12.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        working-directory: ./backend
        run: npm install
      - name: Run build if present
        working-directory: ./backend
        run: npm run build --if-present
      - name: Run tests
        working-directory: ./backend
        run: npm test